encoding: UTF-8
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - _post/Oyster/daily
  - _post/Oyster/quarter
  - slides
  - vendor
  - rakefile

kramdown:
  syntax_highlighter: rouge
  input: GFM

  # Rouge Highlighter in Kramdown â€º //kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1